version: "3.8"

services:
  identity-service:
    build: .
    container_name: identity-service
    restart: always
    depends_on:
      - mongodb
      - redis
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://localhost:27017/f
      - REDIS_URI=redis://localhost:6379
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRE=15m
      - JWT_REFRESH=7d
      - REFRESH_SECRET=your_refresh_secret
      - PORT=5000
      - JWT_REFRESH_EXPIRE=604800
      - SESSION_SECRET=session_secret
      - GOOGLE_CLIENT_ID=clientId
      - GOOGLE_CLIENT_SECRET=client_secret
    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:

